# -*- coding: utf-8 -*-
"""Bono/Pension.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12No1Q9aHEgmLcpJWqx1RADqSm2P4F1Ha
"""

!pip install Faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

# Lista de atributos 
features = [
    "id_Bo",
    "T.Bono",
    "dob",

]# Crea el dataframe con la lista de atributos
df = pd.DataFrame(columns=features)

num_users=5000

#Utilizamos uuid para generar numeros aleatorios 
df['id_Bo'] = [uuid.uuid4().int for i in range(num_users)]

#Verifica que cada numero generado sea único
print(df['id_Bo'].nunique()==num_users)

def random_dob(start, end, n):
    """
    Generar una lista de un número determinado de marcas de tiempo
    """
    
    # El formato de marca de tiempo
    frmt = "%Y-%m-%d"
    
    # Formateo de los dos períodos de tiempo
    stime = datetime.datetime.strptime(start, frmt)
    etime = datetime.datetime.strptime(end, frmt)
    
    # Creando el grupo para tiempos aleatorios
    td = etime - stime
    
    # Generando una lista con los tiempos aleatorios
    times = [(random.random() * td + stime).strftime(frmt) for _ in range(n)]
    
    return times

df['dob'] = random_dob("2005-01-01", "2022-01-01", num_users)

tb = ["Bono Desarrollo Humano", "Pension Adultos Mayores", "Pension mis mejores años", "Pension Discapacidad" , "Contingencias"]
df['T.Bono'] = random.choices(tb , weights=(25,35,20,10,10), k=num_users)

df.to_csv('dataset_users.csv')