# -*- coding: utf-8 -*-
"""Entidad_Financiera.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_PuhiDZwmZjxKgUiNohzA5r4KBMF4qVq
"""

!pip install Faker
import pandas as pd
import uuid
import random
from faker import Faker
import datetime

#Numero de datos sinteticos 
num_users = 5000

# Lista de atributos 
features = [
    "id_FI",
    "name",
    "Estado"

]# Crea el dataframe con la lista de atributos
df = pd.DataFrame(columns=features)

#Utilizamos uuid para generar numeros aleatorios 
df['id_FI'] = [uuid.uuid4().int for i in range(num_users)]

#Verifica que cada numero generado sea único
print(df['id_FI'].nunique()==num_users)

Genero_Bes = ["male", "female", "na"]



df['Genero_Be'] = random.choices(
    Genero_Bes, 
    weights=(47,47,6), 
    k=num_users
)

# Inicializamos Facker para los datos sinteticos
faker = Faker()

def name_gen(Genero_Be):
    """
    Genera el nombre del usuario con respecto al genero 
    ___________
    Tenemos tres opciones definidas como genero 
    male
    female
    na 
    ___________
    Es una función ya que tiene de retorno una de las tres opciones presentadas
    """
    if Genero_Be=='male':
        return faker.name_male()
    elif Genero_Be=='female':
        return faker.name_female()
    
#Genera los datos sinteticos 
    return faker.name()
df['name'] = [name_gen(i) for i in df['Genero_Be']]

Genero_Bes = ["Activo", "Inactivo", "En espera"]

df['Estado'] = random.choices(
    Genero_Bes, 
    weights=(47,47,6), 
    k=num_users
)



df.to_csv('dataset_users.csv')